# Generated by Django 4.2.6 on 2024-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module1', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('suggestions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
