# Generated by Django 4.2.6 on 2024-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_yogi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neha',
            name='phonenumber',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
