# Generated by Django 4.2.6 on 2024-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_neha_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neha',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
